"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import trackerConfig from "../config/tracker.json";

type InsightFields = { id:string; threadUrl:string; dueDate:string|null; completed:number; completedAt:string|null; archived:number; archivedAt:string|null; source:string; createdAt?:string|null; acknowledged?:number; workStatus?:string|null; acknowledgementType?:string|null; acknowledgementDetail?:string|null; insightSummary?:string|null; updatesJson?:string|null; lastCheckedAt?:string|null };
type Assignment = InsightFields & { assignee:string; assignment:string; assignedAt:string };
type MyTask = InsightFields & { requester:string; requestType:string; task:string; askedAt:string };
type ThreadUpdate = { timestamp?:string; author?:string; type?:string; text?:string; emoji?:string; permalink?:string };
type CaptureToast = { id:string; requester:string; task:string; threadUrl:string };
type MonitorRun = { startedAt?:string; finishedAt?:string; outcome?:string; capturedCount?:number; candidateCount?:number; details?:{assignments?:number;myTasks?:number;candidates?:number}; error?:string|null };
type View = "delegated" | "mine";
const NOTIFICATION_PREFERENCE_KEY = "assignment-ledger-my-task-notifications-enabled";
const NOTIFICATION_WATERMARK_KEY = "assignment-ledger-my-task-notification-watermark";
const DIRECT_REPORTS = trackerConfig.assignees.map((person) => person.name);
const MANAGER_NAME = trackerConfig.manager.name || "you";
const REQUEST_TYPES = ["task","question","input","approval","review"] as const;
const todayInput = () => { const d=new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16); };
const parseDate = (value:string) => { const dateOnly=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return dateOnly?new Date(Number(dateOnly[1]),Number(dateOnly[2])-1,Number(dateOnly[3])):new Date(value); };
const localDayKey = (value:Date) => `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;
const formatDate = (value:string|null, withTime=false) => { if(!value)return "No due date"; const d=parseDate(value); if(Number.isNaN(d.getTime()))return value; return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric",...(withTime?{hour:"numeric",minute:"2-digit"}:{})}).format(d); };
const readUpdates = (value?:string|null):ThreadUpdate[] => { if(!value)return []; try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed:[];}catch{return [];} };
const timelineMarker = (u:ThreadUpdate) => u.type!=="reaction"?"↳":(!u.emoji?"●":(/^[a-z0-9_+-]+$/i.test(u.emoji)?"✓":u.emoji));
const initials = (name:string) => name.split(" ").filter(Boolean).map(p=>p[0]).join("").slice(0,3);
function statusLabel(item:InsightFields, view:View){ if(item.archived)return "Archived"; if(item.completed)return "Complete"; if(item.workStatus==="completed")return "Reported complete"; if(item.workStatus==="blocked")return "Blocked"; if(item.workStatus==="waiting_on_me")return "Waiting on you"; if(item.workStatus==="waiting_on_requester")return "Waiting on requester"; if(item.workStatus==="in_progress")return "In progress"; if(item.acknowledged||item.workStatus==="acknowledged")return "Acknowledged"; return view==="delegated"?"Awaiting acknowledgement":"Not started"; }

export function AssignmentTracker(){
  const [view,setView]=useState<View>("delegated"), [assignments,setAssignments]=useState<Assignment[]>([]), [myTasks,setMyTasks]=useState<MyTask[]>([]);
  const [loading,setLoading]=useState(true), [error,setError]=useState(""), [showForm,setShowForm]=useState(false), [search,setSearch]=useState(""), [person,setPerson]=useState("all"), [saving,setSaving]=useState(false);
  const [status,setStatus]=useState<"open"|"complete"|"archived"|"all">("open"), [expanded,setExpanded]=useState<Set<string>>(()=>new Set());
  const [settingsOpen,setSettingsOpen]=useState(false), [notificationsEnabled,setNotificationsEnabled]=useState(true), [monitorEnabled,setMonitorEnabled]=useState(true), [monitorSaving,setMonitorSaving]=useState(false), [fetchingNow,setFetchingNow]=useState(false), [lastMonitorRun,setLastMonitorRun]=useState<MonitorRun|null>(null), [toasts,setToasts]=useState<CaptureToast[]>([]);
  const [now,setNow]=useState(()=>Date.now());
  const notificationReadyRef=useRef(false), notificationWatermarkRef=useRef<number|null>(null), notificationsEnabledRef=useRef(true), toastTimersRef=useRef<Map<string,number>>(new Map());
  const dismissToast=useCallback((id:string)=>{setToasts(current=>current.filter(toast=>toast.id!==id));const timer=toastTimersRef.current.get(id);if(timer)window.clearTimeout(timer);toastTimersRef.current.delete(id);},[]);
  const recordInboundCaptures=useCallback((tasks:MyTask[])=>{if(!notificationReadyRef.current)return;const monitored=tasks.map(task=>({task,capturedAt:Date.parse(task.createdAt||task.askedAt)})).filter(entry=>entry.task.source!=="manual"&&!Number.isNaN(entry.capturedAt)).sort((a,b)=>a.capturedAt-b.capturedAt);if(!monitored.length)return;const latest=monitored[monitored.length-1].capturedAt,current=notificationWatermarkRef.current;if(current===null){notificationWatermarkRef.current=latest;window.localStorage.setItem(NOTIFICATION_WATERMARK_KEY,String(latest));return;}const fresh=monitored.filter(entry=>entry.capturedAt>current);notificationWatermarkRef.current=Math.max(current,latest);window.localStorage.setItem(NOTIFICATION_WATERMARK_KEY,String(notificationWatermarkRef.current));if(!notificationsEnabledRef.current||!fresh.length)return;const additions=fresh.map(({task})=>({id:`${task.id}-${Date.now()}`,requester:task.requester,task:task.task,threadUrl:task.threadUrl}));setToasts(existing=>[...existing,...additions].slice(-4));for(const toast of additions){const timer=window.setTimeout(()=>dismissToast(toast.id),10000);toastTimersRef.current.set(toast.id,timer);}},[dismissToast]);
  const loadData=useCallback(async(quiet=false)=>{try{const [a,t]=await Promise.all([fetch("/api/assignments",{cache:"no-store"}),fetch("/api/my-tasks",{cache:"no-store"})]);const [ap,tp]=await Promise.all([a.json(),t.json()]);if(!a.ok)throw new Error(ap.error||"Could not load assignments");if(!t.ok)throw new Error(tp.error||"Could not load your tasks");setAssignments(ap.assignments);setMyTasks(tp.tasks);recordInboundCaptures(tp.tasks);setError("");}catch(c){if(!quiet)setError(c instanceof Error?c.message:"Could not load the local ledger");}finally{setLoading(false);}},[recordInboundCaptures]);
  const loadMonitorState=useCallback(async()=>{const [settingResponse,runResponse]=await Promise.all([fetch("/api/settings/monitor",{cache:"no-store"}),fetch("/__local/monitor/status",{cache:"no-store"})]);const setting=await settingResponse.json();if(!settingResponse.ok)throw new Error(setting.error||"Could not read monitor settings");setMonitorEnabled(setting.enabled!==false);setLastMonitorRun(setting.lastRun||null);if(runResponse.ok){const run=await runResponse.json();setFetchingNow(Boolean(run.running));if(!run.running&&run.outcome)setLastMonitorRun(run);}},[]);
  useEffect(()=>{const toastTimers=toastTimersRef.current;const initial=window.setTimeout(()=>{const storedWatermark=Number(window.localStorage.getItem(NOTIFICATION_WATERMARK_KEY));notificationWatermarkRef.current=Number.isFinite(storedWatermark)&&storedWatermark>0?storedWatermark:null;void Promise.all([fetch("/api/settings/notifications",{cache:"no-store"}).then(response=>response.json()).then(payload=>{const enabled=payload.enabled!==false;setNotificationsEnabled(enabled);notificationsEnabledRef.current=enabled;window.localStorage.setItem(NOTIFICATION_PREFERENCE_KEY,String(enabled));}).catch(()=>{const enabled=window.localStorage.getItem(NOTIFICATION_PREFERENCE_KEY)!=="false";setNotificationsEnabled(enabled);notificationsEnabledRef.current=enabled;}),loadMonitorState().catch(()=>{})]).finally(()=>{notificationReadyRef.current=true;void loadData();});},0);const timer=window.setInterval(()=>{setNow(Date.now());void loadData(true);if(fetchingNow)void loadMonitorState();},5000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);for(const toastTimer of toastTimers.values())window.clearTimeout(toastTimer);toastTimers.clear();};},[fetchingNow,loadData,loadMonitorState]);
  const delegated=view==="delegated", rows: (Assignment|MyTask)[]=delegated?assignments:myTasks;
  const statusRows=useMemo(()=>rows.filter(i=>{if(status==="open")return !i.completed&&!i.archived;if(status==="complete")return Boolean(i.completed)&&!i.archived;if(status==="archived")return Boolean(i.archived);return !i.archived;}),[rows,status]);
  const people=useMemo(()=>delegated?[...DIRECT_REPORTS]:[...new Set(statusRows.map(i=>(i as MyTask).requester))].sort(),[delegated,statusRows]);
  const metrics=useMemo(()=>{const today=localDayKey(new Date(now)),todayStart=parseDate(today).getTime(),next=todayStart+604800000;return{open:rows.filter(i=>!i.completed&&!i.archived).length,complete:rows.filter(i=>Boolean(i.completed)&&!i.archived&&Boolean(i.completedAt)&&localDayKey(new Date(i.completedAt!))===today).length,dueSoon:rows.filter(i=>!i.completed&&!i.archived&&i.dueDate&&parseDate(i.dueDate).getTime()>=todayStart&&parseDate(i.dueDate).getTime()<=next).length};},[now,rows]);
  const visible=useMemo(()=>{const needle=search.trim().toLowerCase();return statusRows.filter(i=>{const name="assignee" in i?i.assignee:i.requester,text="assignment" in i?i.assignment:i.task;if(person!=="all"&&name!==person)return false;return !needle||`${name} ${text}`.toLowerCase().includes(needle);});},[person,search,statusRows]);
  function changeView(next:View){setView(next);setSearch("");setPerson("all");setStatus("open");setExpanded(new Set());}
  function changeStatus(next:typeof status){setStatus(next);setPerson("all");}
  async function toggleNotifications(){const enabled=!notificationsEnabled;setNotificationsEnabled(enabled);notificationsEnabledRef.current=enabled;window.localStorage.setItem(NOTIFICATION_PREFERENCE_KEY,String(enabled));if(!enabled){for(const timer of toastTimersRef.current.values())window.clearTimeout(timer);toastTimersRef.current.clear();setToasts([]);}try{const response=await fetch("/api/settings/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled})});if(!response.ok)throw new Error("Could not save notification preference");}catch(c){setNotificationsEnabled(!enabled);notificationsEnabledRef.current=!enabled;window.localStorage.setItem(NOTIFICATION_PREFERENCE_KEY,String(!enabled));setError(c instanceof Error?c.message:"Could not save notification preference");}}
  async function toggleMonitor(){const enabled=!monitorEnabled;setMonitorSaving(true);setError("");try{const response=await fetch("/api/settings/monitor",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Could not save monitor setting");const local=await fetch("/__local/monitor/control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({enabled})});const localPayload=await local.json();if(!local.ok)throw new Error(localPayload.error||"Could not update the local listener");setMonitorEnabled(enabled);}catch(c){await fetch("/api/settings/monitor",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:!enabled})}).catch(()=>{});setError(c instanceof Error?c.message:"Could not update monitor setting");}finally{setMonitorSaving(false);}}
  async function fetchLatest(){setFetchingNow(true);setError("");try{const response=await fetch("/__local/monitor/run",{method:"POST"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Could not start full fetch");setLastMonitorRun(payload);}catch(c){setFetchingNow(false);setError(c instanceof Error?c.message:"Could not start full fetch");}}
  async function createRecord(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const body=Object.fromEntries(new FormData(event.currentTarget).entries());try{const response=await fetch(delegated?"/api/assignments":"/api/my-tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Could not save record");if(delegated)setAssignments(c=>[payload.assignment,...c]);else setMyTasks(c=>[payload.task,...c]);setShowForm(false);event.currentTarget.reset();}catch(c){setError(c instanceof Error?c.message:"Could not save record");}finally{setSaving(false);}}
  async function toggleComplete(item:Assignment|MyTask){const completed=!item.completed,completedAt=completed?new Date().toISOString():null,endpoint=delegated?`/api/assignments/${item.id}`:`/api/my-tasks/${item.id}`;if(delegated)setAssignments(c=>c.map(r=>r.id===item.id?{...r,completed:Number(completed),completedAt}:r));else setMyTasks(c=>c.map(r=>r.id===item.id?{...r,completed:Number(completed),completedAt}:r));const response=await fetch(endpoint,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({completed})});if(!response.ok){await loadData(true);const p=await response.json();setError(p.error||"Could not update record");}}
  async function toggleArchive(item:Assignment|MyTask){const archived=!item.archived,endpoint=delegated?`/api/assignments/${item.id}`:`/api/my-tasks/${item.id}`;if(delegated)setAssignments(c=>c.map(r=>r.id===item.id?{...r,archived:Number(archived)}:r));else setMyTasks(c=>c.map(r=>r.id===item.id?{...r,archived:Number(archived)}:r));const response=await fetch(endpoint,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({archived})});if(!response.ok){await loadData(true);const p=await response.json();setError(p.error||"Could not update archive state");}}
  function toggleContext(id:string){setExpanded(c=>{const n=new Set(c);if(n.has(id))n.delete(id);else n.add(id);return n;});}
  return <main className="shell">
    <div className="navigation-row"><nav className="view-tabs" aria-label="Assignment ledgers"><button type="button" className={delegated?"active":""} onClick={()=>changeView("delegated")}>Direct Report Assignments</button><button type="button" className={!delegated?"active":""} onClick={()=>changeView("mine")}>My Tasks and Assignments</button></nav><div className="nav-actions">{!monitorEnabled&&<button className={`quick-fetch-button ${fetchingNow?"is-running":""}`} type="button" aria-label={fetchingNow?"Fetching latest tasks & assignments":"Fetch latest tasks & assignments"} title={fetchingNow?"Fetching latest tasks & assignments…":"Fetch latest tasks & assignments"} disabled={fetchingNow} onClick={()=>void fetchLatest()}><span aria-hidden="true">🏃</span></button>}<div className="settings-wrap"><button className="settings-button" type="button" aria-label="Monitor and notification settings" aria-expanded={settingsOpen} onClick={()=>setSettingsOpen(open=>!open)}>⚙</button>{settingsOpen&&<section className="settings-popover" aria-label="Monitor and notification settings"><div><strong>Settings</strong><button className="settings-close" type="button" aria-label="Close settings" onClick={()=>setSettingsOpen(false)}>×</button></div><div className="notification-setting"><span><strong>Heartbeat monitor</strong><small>Capture Slack work locally and use Codex for context and decisions every 15 minutes.</small></span><label className="toggle-control"><input type="checkbox" aria-label="Enable heartbeat monitor" checked={monitorEnabled} disabled={monitorSaving||fetchingNow} onChange={()=>void toggleMonitor()}/><i aria-hidden="true"/></label></div><div className="settings-divider"/><div className="notification-setting"><span><strong>Desktop notifications</strong><small>Show an operating-system notification when the listener captures a new request for you, even when the dashboard is closed.</small></span><label className="toggle-control"><input type="checkbox" aria-label="Enable desktop notifications" checked={notificationsEnabled} onChange={()=>void toggleNotifications()}/><i aria-hidden="true"/></label></div><p>{lastMonitorRun?.finishedAt?`Last fetch ${formatDate(lastMonitorRun.finishedAt,true)}${lastMonitorRun.outcome==="error"?" · failed":""}.`:monitorEnabled?"Monitoring is active.":"Monitoring is paused."}</p></section>}</div></div></div>
    <header className="topbar"><div><p className="eyebrow">{delegated?"Direct report assignments":"Requests for me"}</p><h1>{delegated?"Assignment ledger":"My work ledger"}</h1><p className="subtitle">{delegated?"A local record of work you’ve delegated, from assignment to completion.":"Questions, requests, and decisions directed to you across Slack."}</p></div><button className="primary" type="button" onClick={()=>setShowForm(true)}>+ Add {delegated?"assignment":"task"}</button></header>
    {error&&<div className="error" role="alert">{error}</div>}
    <section className="summary" aria-label="Assignment summary"><article><span>Open</span><strong>{metrics.open}</strong><small>{metrics.open?"Still in motion":"Nothing outstanding"}</small></article><article><span>Due soon</span><strong>{metrics.dueSoon}</strong><small>Next 7 days</small></article><article><span>Complete</span><strong>{metrics.complete}</strong><small>Today</small></article></section>
    <section className="ledger"><div className="ledger-head"><div><h2>{delegated?"Assignments":"My tasks and assignments"}</h2><p>{delegated?"Tracking only your seven selected direct reports.":"Only actionable questions, requests, reviews, and decisions addressed to you."}</p></div><span className={`live ${monitorEnabled?"":"paused"}`}><i/> {fetchingNow?"Fetching latest tasks…":monitorEnabled?"Slack capture · every 15 min":"Slack capture · paused"}</span></div>
      <div className="toolbar"><label className="search"><span>⌕</span><input aria-label="Search records" placeholder={delegated?"Search assignments":"Search my tasks"} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="filters"><select aria-label="Filter by person" value={person} onChange={e=>setPerson(e.target.value)}><option value="all">{delegated?"All direct reports":"All requesters"}</option>{people.map(name=><option key={name}>{name}</option>)}</select><div className="segmented" aria-label="Filter by status">{(["open","complete","archived","all"] as const).map(value=><button key={value} type="button" className={status===value?"active":""} onClick={()=>changeStatus(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div></div></div>
      {loading?<div className="empty"><div className="loader"/><p>Loading your local ledger…</p></div>:visible.length===0?<div className="empty"><div className="empty-mark">✓</div><h3>{rows.length?"No matching records":delegated?"No assignments captured yet":"No tasks directed to you yet"}</h3><p>{rows.length?"Try changing your filters.":"New Slack items will appear here with their source, context, and due date."}</p></div>:<div className="assignment-list">{visible.map(item=>{
        const name="assignee" in item?item.assignee:item.requester,text="assignment" in item?item.assignment:item.task,occurredAt="assignedAt" in item?item.assignedAt:item.askedAt,updates=readUpdates(item.updatesJson),isOpen=expanded.has(item.id),overdue=!item.completed&&item.dueDate&&localDayKey(parseDate(item.dueDate))<localDayKey(new Date(now));
        return <article className={`assignment ${item.completed?"is-complete":""} ${item.archived?"is-archived":""} ${isOpen?"is-expanded":""}`} key={item.id}><button className="check" type="button" disabled={Boolean(item.archived)} aria-label={item.completed?`Reopen ${text}`:`Mark ${text} complete`} aria-pressed={Boolean(item.completed)} onClick={()=>toggleComplete(item)}>{item.completed?"✓":""}</button><div className="assignment-main"><div className="assignment-meta"><span className="avatar">{initials(name)}</span><strong>{name}</strong><span>{delegated?"Assigned":"Requested"} {formatDate(occurredAt,true)}</span>{!delegated&&"requestType" in item&&<span className="request-type">{item.requestType}</span>}<span className={`source ${item.source!=="manual"?"auto":""}`}>{item.source!=="manual"?"Auto-captured":"Manual"}</span></div><p>{text}</p><div className="assignment-foot"><span className={overdue?"overdue":""}>◷ {overdue?"Overdue · ":"Due · "}{formatDate(item.dueDate)}</span><span className={`progress-pill status-${item.archived?"archived":item.workStatus||"new"}`}>{statusLabel(item,view)}</span><button className="context-button" type="button" aria-expanded={isOpen} onClick={()=>toggleContext(item.id)}>{isOpen?"Hide context ↑":"View context ↓"}</button>{(item.completed||item.archived)&&<button className="archive-button" type="button" onClick={()=>toggleArchive(item)}>{item.archived?"Unarchive":"Archive"}</button>}<a className="source-link" href={item.threadUrl} target="_blank" rel="noopener noreferrer">Open source thread ↗</a></div>
        {isOpen&&<div className="context-panel"><div className="context-overview"><div><span>Acknowledgement</span><strong>{item.acknowledged?"Received":"Not yet"}</strong><small>{item.acknowledgementDetail||(delegated?"No reply or reaction from the assignee.":"No reply or reaction from you yet.")}</small></div><div><span>Current signal</span><strong>{statusLabel(item,view)}</strong><small>{item.insightSummary||"No progress context found yet."}</small></div></div><div className="timeline-head"><h4>Thread activity</h4><span>{item.lastCheckedAt?`Checked ${formatDate(item.lastCheckedAt,true)}`:"Waiting for first thread review"}</span></div>{updates.length?<ol className="timeline">{updates.map((u,index)=><li key={`${u.timestamp||"update"}-${index}`}><span className="timeline-dot">{timelineMarker(u)}</span><div><div><strong>{u.author||(delegated?name:MANAGER_NAME)}</strong><time>{formatDate(u.timestamp||null,true)}</time></div><p>{u.text||(u.emoji?`Reacted with ${u.emoji}`:"Updated the thread")}</p>{u.permalink&&<a className="source-link timeline-link" href={u.permalink} target="_blank" rel="noopener noreferrer">View update ↗</a>}</div></li>)}</ol>:<div className="no-updates">{delegated?`No replies or reactions from ${name} yet.`:"No reply, reaction, or progress update from you yet."}</div>}</div>}</div></article>;
      })}</div>}
    </section><footer><span>Data and scan checkpoints stay on this computer</span><span>{delegated?`Monitoring Slack for ${DIRECT_REPORTS.length} selected assignees`:`Monitoring Slack for requests directed to ${MANAGER_NAME}`}</span></footer>
    <aside className="toast-region" aria-live="polite" aria-label="New task notifications">{toasts.map(toast=><article className="capture-toast" role="status" key={toast.id}><div className="toast-icon">✓</div><div><div className="toast-title"><strong>New task captured</strong><button type="button" aria-label="Dismiss notification" onClick={()=>dismissToast(toast.id)}>×</button></div><small>From {toast.requester}</small><p>{toast.task}</p><div className="toast-actions"><button type="button" onClick={()=>{changeView("mine");dismissToast(toast.id);}}>Open ledger</button><a href={toast.threadUrl} target="_blank" rel="noopener noreferrer">View source ↗</a></div></div></article>)}</aside>
    {showForm&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setShowForm(false);}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="form-title"><div className="modal-head"><div><p className="eyebrow">New record</p><h2 id="form-title">Add {delegated?"assignment":"my task"}</h2></div><button className="close" type="button" aria-label="Close" onClick={()=>setShowForm(false)}>×</button></div><form onSubmit={createRecord}>{delegated?<label>Assigned to<select name="assignee" required defaultValue=""><option value="" disabled>Select a direct report</option>{DIRECT_REPORTS.map(name=><option key={name}>{name}</option>)}</select></label>:<><label>Requested by<input name="requester" required placeholder="Name or Slack display name"/></label><label>Request type<select name="requestType" defaultValue="task">{REQUEST_TYPES.map(type=><option key={type} value={type}>{type[0].toUpperCase()+type.slice(1)}</option>)}</select></label></>}<label>{delegated?"What was assigned":"What is being asked"}<textarea name={delegated?"assignment":"task"} required rows={4} placeholder="Describe the expected outcome…"/></label><label>Source thread URL<input name="threadUrl" type="url" required placeholder="https://…"/></label><div className="form-row"><label>{delegated?"Assigned at":"Asked at"}<input name={delegated?"assignedAt":"askedAt"} type="datetime-local" required defaultValue={todayInput()}/></label><label>Due date <em>optional</em><input name="dueDate" type="date"/></label></div><div className="form-actions"><button className="secondary" type="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary" type="submit" disabled={saving}>{saving?"Saving…":"Save record"}</button></div></form></section></div>}
  </main>;
}
